package uk.gov.moj.cpp.defence.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - disassociate defence organisation"
  when
    $outcome: Outcome();
    $action: Action(name == "defence.disassociate-defence-organisation");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Associate", "Court Clerks", "Court Administrators", "Crown Court Admin", "Listing Officers", "Legal Advisers", "System Users","Chambers Clerk","Chambers Admin","Defence Lawyers", "Advocates"));
  then
    $outcome.setSuccess(true);
end


